language: R
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
cache: packages

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

matrix:
  include:
    - r: release
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")' -e 'remotes::install_github("tidyverse/tidytemplate")' -e 'remotes::install_cran("tidyverse")' -e 'remotes::install_github("hadley/emoe")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
